### ISSUE TITLE
Uknown  './tmp/points3d.ply' ?

### ISSUE THREAD

**Issue by limaolin924** [heheyas/V3D#16]

**Comment by linmi1** [comment]
the same question!have anyone solved it?

**Comment by huhuhuxiao** [comment]
Create the `tmp` folder under the `V3D` folder can solve this problem.
<img width="209" alt="1712396898824" src="https://github.com/heheyas/V3D/assets/73291920/2af46845-f0b2-4257-ac81-5822547e5cea">
