### ISSUE TITLE
Python version requirement？

### ISSUE THREAD

**Issue by forrest-lam** [heheyas/V3D#3]
python 3.8.16 error:
<img width="935" alt="image" src="https://github.com/heheyas/V3D/assets/135090192/1390725d-79ec-4110-b3c6-62ada027d200">

**Comment by Yzhbuaa** [comment]
If you are using python 3.8, I'd recommend to rewrite line 1135 as:

``` python
def forward(self, batch: Dict, force_zero_embeddings: List = None) -> Dict: 
```

There are other lines which complains about the same error, which is caused by the version of python, you can rewrite them as well.

**Comment by qixuanwang-233** [comment]
In Python 3.10 and higher versions, you can use | symbols to represent the type joint (for example, the List | None said parameter can be a List type or None type), but in Python 3.9 and the following version that is not supported.
